language: d
d:
    - dmd
    - ldc-1.8.0

os:
    - linux

sudo: required
group: edge
dist: trusty

notifications:
    email: false

git:
    depth: 1

branches:
    only:
        - master

script: ./travis.sh
